services:
  db:
    image: postgres:15-alpine
    container_name: checkout-db-container
    restart: always
    environment:
      POSTGRES_USER: user_checkout
      POSTGRES_PASSWORD: password_123
      POSTGRES_DB: checkout_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: